version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: